#!/usr/bin/env python3
import json
from pathlib import Path
import pandas as pd
O=Path('outputs/night4a_handoff'); E=O/'evidence_repair'
commits={'SpatialGlue':'7c976d811d27ace51ce47ae0ad94a068a7d222fa','Seurat':'79c466c0e61e89aa299ee767fec3b69afda47301','COSMOS':'56ea355be51e64d9253e2871b8bd447fdfd0d230','ARISE':'fefdd849494c0d08e755052a7a31b20169945e40','SMART':'75676546a66d48a7ebfd7c5f3a2758a4c538fcfc'}
reasons={'SpatialGlue':'official notebook requires unavailable stgat kernel; retry venv lacked nbconvert entry','Seurat':'no executable R/Rscript; no WNN graph, modality weights or clusters','COSMOS':'package absent; retry venv lacked nbconvert entry','ARISE':'torch_geometric absent; retry venv lacked nbconvert entry','SMART':'muon absent and author-local R path hard-coded; retry venv lacked nbconvert entry'}
rows=[{'method':m,'official_commit':c,'tutorial_status':'UNREPRODUCIBLE','attempt1_preserved':True,'compatibility_retry_count':0 if m=='Seurat' else 1,'scientific_formula_modified':False,'root_cause':reasons[m],'eligible_night4b':False} for m,c in commits.items()]
pd.DataFrame(rows).to_csv(O/'baseline_reproducibility_matrix.csv',index=False);(O/'baseline_reproducibility_matrix.json').write_text(json.dumps(rows,indent=2)+'\n')
ds=['gse263617_d1_ln','gse263617_a1_tonsil','gse263617_d1_tonsil','gse198353_spleen_rep1','gse198353_spleen_rep2'];methods=['SpaLORA_FULL_IGE','SpaLORA_UNIFORM_CROSS','SpaLORA_UNIFORM_WITHIN']+list(commits);mat=[]
for d in ds:
 for m in methods: mat.append({'dataset':d,'method':m,'task_match':True,'observation_alignment':'locked_preflight','tutorial_status':'NOT_APPLICABLE' if m.startswith('SpaLORA') else 'UNREPRODUCIBLE','commit':None if m.startswith('SpaLORA') else commits[m],'common_fairness_layer':'same observations labels evaluator','k_protocol':'authoritative K only; no accuracy if no labels','seeds':'0,1,2,3,4','pre_exclusion_reason':None if m.startswith('SpaLORA') else 'official tutorial incomplete','future_interface':'embedding+cluster+resource'})
pd.DataFrame(mat).to_csv(O/'night4b_benchmark_matrix_proposal.csv',index=False);(O/'night4b_benchmark_matrix_proposal.json').write_text(json.dumps(mat,indent=2)+'\n')
(O/'night4b_protocol_draft.json').write_text(json.dumps({'status':'DRAFT_NOT_EXECUTED','data_roles':['development','held-out confirmation','untouched independent'],'seeds':[0,1,2,3,4],'run_order':'dataset-method-seed','label_firewall':True,'metrics':['ARI','NMI','AMI','Homogeneity','neighbor agreement','Moran I','Geary C','per-domain','runtime','CPU/GPU peak'],'failures_retained':True,'equal_tuning_budget':True,'common_evaluator':True,'architecture_candidates':['FULL_IGE','UNIFORM_CROSS','UNIFORM_WITHIN'],'night4b_executed':False},indent=2)+'\n')
qa=json.loads((E/'figure_qa_manifest.json').read_text());qa['status']='PNG_STRUCTURAL_PASS_PDF_LOCAL_RENDER_PENDING';qa['publication_ready']=False
for x in qa['figures']:x['visual_qa_status']='DIAGNOSTIC_ONLY_PENDING_LOCAL_PDF_RENDER_REVIEW'
(E/'figure_qa_manifest.json').write_text(json.dumps(qa,indent=2,sort_keys=True)+'\n')
dev=[{'stage':'P1','event':'three failed implementation attempts retained before exact round-trip parser/rule correction','scientific_effect':'none'},{'stage':'P2','event':'slow single download replaced by audited Range downloader; partial retained','scientific_effect':'none'},{'stage':'P3','event':'bounded official attempts and one compatibility retry failed','scientific_effect':'no benchmark produced'}]
(O/'protocol_deviations.json').write_text(json.dumps(dev,indent=2)+'\n')
c={'gate':'BLOCKED_PREFLIGHT','night3b_original_results_changed':False,'night3b_decision_changed':False,'night3b_decision':'MIXED_EVIDENCE','formal_benchmark_run':False,'semantic_label_access_after_lock':True,'core_baselines_complete':0,'core_baselines_total':5,'held_out_accuracy_eligible':['gse263617_d1_ln'],'independent_accuracy_eligible':[],'night4b_started':False}
for n in ('night4a_completion.json','night4a_gate_status.json'):(O/n).write_text(json.dumps(c,indent=2)+'\n')
(O/'resource_summary.json').write_text(json.dumps({'gpu':'RTX 4080 SUPER 32760 MiB','ram_total':'503 GiB','data_disk_free_start':'190 GiB','formal_training_runs':0},indent=2)+'\n')
(O/'night4a_report.md').write_text('''# SpaLORA Night-4A report\n\n**Gate: BLOCKED_PREFLIGHT**\n\n- Night-3B original results changed: **NO**.\n- Night-3B decision changed: **NO - MIXED_EVIDENCE**.\n- Formal benchmark run: **NO**.\n- Semantic labels accessed only after preprocessing lock: **YES**.\n\n## Evidence repair\nLower-is-better counts were regenerated without overwriting Night-3B. Exact round-trip recomputation preserved 120 keys, summaries, paired deltas and MIXED_EVIDENCE. Ten PNG/PDF figure pairs were redrawn; they remain diagnostic until local PDF visual QA is complete.\n\n## Data preflight\nD1 lymph node is accuracy-eligible with paired RNA/protein, coordinates and ten-domain manual ground truth. A1/D1 tonsil have no auditable semantic label column. Independent GSE198353 provides two aligned RNA+protein spleen replicates with coordinates but no official manual domain labels, so only the label-free layer is eligible. GSE213264 lacks reproducible paired spatial coordinates. The data gate fails.\n\n## Baselines\nAll five official repositories and commits were locked. Attempt 1 and at most one compatibility-only retry were retained. SpatialGlue, Seurat/WNN, COSMOS, ARISE and SMART are UNREPRODUCIBLE in this bounded target-machine preflight; 0/5 reached integrated embedding and official clustering. No scientific formula or parameter was changed.\n\n## Decision\nNight-3B evidence repair preserved all locked numerical results and the preregistered `MIXED_EVIDENCE` decision. Candidate external datasets and baseline implementations were evaluated for provenance, task compatibility, and end-to-end reproducibility before any formal benchmark outcome was generated. The project is `BLOCKED_PREFLIGHT`. Night-4B was not started.\n''')
print('NIGHT4A_FINAL_METADATA BLOCKED_PREFLIGHT')
