#!/usr/bin/env python3
"""Finalize the preregistered BASELINE_REPLAY_MISMATCH hard stop."""
from __future__ import annotations
import csv, hashlib, json, os, pathlib, statistics
import pandas as pd
R=pathlib.Path(__file__).resolve().parents[1];O=R/'outputs/night5d_handoff';RAW=pathlib.Path('/root/autodl-fs/night5d_raw_runs_20260814')
def atom(p,o):
 p.parent.mkdir(parents=True,exist_ok=True);q=p.with_suffix(p.suffix+'.tmp');q.write_text(json.dumps(o,indent=2,sort_keys=True),encoding='utf8');os.replace(q,p)
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def csvwrite(p,rows):
 keys=sorted({k for r in rows for k in r});f=p.open('w',newline='',encoding='utf8');w=csv.DictWriter(f,fieldnames=keys);w.writeheader();w.writerows(rows);f.close()
def main():
 audit=json.load(open(O/'baseline_reuse_and_extension_audit.json'));assert not audit['all_match'];failed=[x for x in audit['historical_seeds'] if not x['within_1e_12']];assert len(failed)==5
 rows=[]
 for cid in ('B00_C00_FULL_IGE','B01_C04_SHRINK25','B10_SHRINK25_ANCHOR10','C09_RNA_ANCHOR10'):
  seeds=range(5,10) if cid.startswith('B00') else range(10)
  for seed in seeds:
   m=json.load(open(RAW/cid/f'seed_{seed}'/'run_manifest.json'));rows.append({'candidate_id':cid,'seed':seed,'effective_end_to_end_runtime_seconds':m['timings']['training_seconds'],'gpu_peak_allocated_mib':m['resources']['gpu_peak_allocated_mib'],'model_state_sha256':m['saved_model_state_sha256']})
 for seed in range(10):
  m=json.load(open(RAW/'C09_RNA_ANCHOR10'/f'seed_{seed}'/'run_manifest.json'));rows.append({'candidate_id':'B17_C09_DIFFUSE10','seed':seed,'effective_end_to_end_runtime_seconds':m['timings']['training_seconds'],'gpu_peak_allocated_mib':m['resources']['gpu_peak_allocated_mib'],'model_state_sha256':'source:'+m['saved_model_state_sha256']})
 csvwrite(O/'p22_resource_accounting.csv',rows)
 reason={'status':'NOT_RUN','hard_stop':'BASELINE_REPLAY_MISMATCH','reason':'historical B00 boundary_disagreement failed the locked 1e-12 replay tolerance; no post-hoc metric substitution permitted','primary_tests_executed':0,'secondary_tests_executed':0,'bootstrap_replicates_executed':0,'signflip_permutations_executed':0}
 atom(O/'p22_primary_exact_tests.json',dict(reason,family='three preregistered primary contrasts'))
 atom(O/'p22_secondary_mechanistic_tests.json',dict(reason,family='two preregistered secondary contrasts'))
 atom(O/'p22_spatial_protection.json',dict(reason,gate_evaluated=False))
 csvwrite(O/'p22_candidate_summary.csv',[{'status':'NOT_RUN_BASELINE_REPLAY_MISMATCH','candidate_id':'NA','note':'No candidate-level summary or method ranking was produced after the hard gate failed.'}])
 atom(O/'p22_confirmatory_decision.json',{'schema_version':1,'termination_status':'BASELINE_REPLAY_MISMATCH','confirmed_balanced_candidates':[],'primary_tests_executed':0,'secondary_tests_executed':0,'training_units_completed':35,'deterministic_transforms_completed':10,'p22_metric_rows_frozen_before_replay_gate':50,'failed_historical_seeds':[x['seed'] for x in failed],'failed_metric':'boundary_disagreement','max_abs_differences_by_seed':{str(x['seed']):x['max_abs_difference'] for x in failed},'other_historical_metrics_match':True,'method_changes_after_label_open':False,'candidate_ranking_performed':False,'d1_run':False,'gse198353_run':False,'night4b_run':False,'formal_benchmark_run':False})
 atom(O/'protocol_deviations.json',{'schema_version':1,'deviations':[{'stage':'preflight','attempt':1,'type':'authority_overreach_in_original_taskbook','scientific_impact':'none; 0 training, 0 transform, 0 label access','retained_record':'preflight_attempt1_blocked_authority_overreach.json'},{'stage':'P0-CONFIRM','attempt':1,'type':'assumed_nonexistent_P22_Night5A_label_free_artifact_directory','resolution':'used the taskbook-authorized immutable Night-3AF P22 cache to deterministically derive only the registered eta=1.0 anchor graph','scientific_impact':'none; 0 training, 0 transform, 0 label access'},{'stage':'P0-CONFIRM','attempt':2,'type':'bitwise GPU perturbation check exceeded exact equality','resolution':'measured unperturbed repeat envelope; attention perturbation difference equaled ordinary CUDA sparse-repeat difference and attention gradients were zero/None','scientific_impact':'none; 0 training, 0 transform, 0 label access'},{'stage':'postlock_evaluation','attempt':1,'type':'historical table omitted derived q column','resolution':'frozen 50-row metric table retained; q derived from ARI/NMI without reopening labels','scientific_impact':'no method changes; aggregation-only resume'},{'stage':'baseline_replay','type':'boundary_disagreement_definition_mismatch','resolution':'hard stop; no primary or secondary tests','scientific_impact':'confirmatory candidate conclusion unavailable'}]})
 p0=json.load(open(O/'p0_confirmatory_contract.json'));lock=json.load(open(O/'locked_p22_training_and_transform_manifest.json'));fw=json.load(open(O/'label_firewall.json'))
 report=f'''# SpaLORA Night-5D locked P22 confirmation report\n\n## Final status\n\n`BASELINE_REPLAY_MISMATCH` (preregistered hard stop). No locked-candidate win/loss conclusion was produced.\n\n## Execution completeness before the hard stop\n\n- Authority parent: `f8bba65ff3f1a3dacf310dd12f81f8b379315b22`.\n- P0-CONFIRM passed: REV1 historical evidence 5/5, historical initial-state/no-label probes 5/5, runtime semantic contracts 4/4.\n- New training: 35/35; deterministic B17 transforms: 10/10; failures: 0.\n- Historical B00 seeds 0-4 were not retrained or overwritten. Their absent final weight files remain expected under the original Night-3B contract.\n- All new training units saved a final `model_state.pt`, a 10-row checkpoint index, and SHA-protected outputs.\n- The label firewall passed. P22 labels were opened once only after the 35+10 total lock.\n\n## Hard-stop evidence\n\nHistorical B00 replay reproduced ARI, NMI, neighbor agreement, Moran's I and Geary C exactly for seeds 0-4. Derived Q differed by at most `5.55e-17`. Boundary disagreement alone differed for every historical seed:\n\n| seed | absolute boundary difference |\n|---:|---:|\n'''+''.join(f"| {x['seed']} | {x['differences']['boundary_disagreement']:.16g} |\n" for x in failed)+'''\nThe mismatch is consistent with a boundary edge-counting definition difference between the historical table and the current evaluator, but the locked protocol did not authorize substituting a metric definition after labels opened. Therefore the `1e-12` replay gate failed exactly as written.\n\n## Statistical consequence\n\nThe three primary exact sign-flip tests, Holm correction, 100,000-replicate paired bootstrap, spatial protection decisions, and two secondary mechanistic contrasts were **not run**. The frozen 50-row metric table is retained as diagnostic evidence only and was not used to rank or modify candidates.\n\n## Semantic and reproducibility audit\n\n- C09/B17 source forward used exact `[0.5, 0.5]` fusion weights. Attention gradients were zero/None; parameter perturbation stayed within the measured CUDA sparse-repeat envelope.\n- B17 used one alpha=0.10 diffusion step from each corresponding frozen C09 embedding and immutable normalized sparse P22 adjacency.\n- D1, GSE198353, Night-4B and formal external benchmark were not opened or run.\n- Night-3B final weights remain unavailable and no Night-3AF weights were substituted. Historical weight-level analysis remains forbidden.\n\n## Scientific interpretation\n\nNight-5D cannot support a confirmatory method claim because the preregistered baseline replay gate failed before confirmatory statistics. This is not evidence that a candidate won or lost; it is a metric-provenance inconsistency requiring planner review. No post-hoc repair or candidate tuning was attempted.\n'''
 (O/'night5d_report.md').write_text(report,encoding='utf8')
 atom(O/'night5d_completion.json',{'schema_version':1,'termination_status':'BASELINE_REPLAY_MISMATCH','p0_confirm_pass':p0['passed'],'training_count':lock['training_count'],'transform_count':lock['transform_count'],'failure_count':lock['failure_count'],'label_firewall_pass':fw['passed'],'primary_tests_executed':0,'secondary_tests_executed':0,'report_sha256':sha(O/'night5d_report.md')})
 atom(O/'budget_audit.json',{'training_planned':35,'training_completed':35,'transforms_planned':10,'transforms_completed':10,'training_budget_exceeded':False,'seed_search':False,'candidate_addition':False,'parameter_change':False})
 atom(O/'shutdown_readiness.json',{'ready_after_git_push_delivery_and_dual_sha':False,'last_remote_command_required':'/usr/bin/shutdown','shutdown_not_yet_dispatched':True})
 print('HARDSTOP_FINALIZED BASELINE_REPLAY_MISMATCH')
if __name__=='__main__':main()
